### PR TITLE
Implement Parser for tuples

### PR DESCRIPTION
**Pull request by kompass**
Hello ! My first PR to this project.

This PR does :
- Implement the issue #1417.
- Add some test.
- Modify the `fn tuple` to use this new feature.

### CODE REVIEW

**Comment by kompass** [comment]
I think the `tuple` function is still useful in case the tuple in question is not composed in another parser. Indeed, tuples implement `Parser`, not` FnMut`, so it is impossible to parse in the same way as other parsers. This code doesn't compile : 
```rust
let (i, result) = (parser1, parser2)(i);
````

To maintain consistency in calls, I think it could be a good idea to keep it. The trait `Tuple` is now only used to be able to implement this function, I don't see any other way.

**Comment by Stargateur** [comment]
I don't follow you, you want use it as documentation ? Unless I miss something remove `Tuple` trait the code still compile.

**Comment by kompass** [comment]
The `Tuple` trait is still used to implement the `tuple` function.

We can still do :
```rust
let (i, result) = tuple((parser1, parser2)(i)?;
```

**Comment by Geal** [comment]
sorry for the delay, it is now merged! I removed the `parse` combinator as it is not really necessary, but the rest was great, thanks for your help!

**Pull request merged**
