### PR TITLE
add dns-parser to readme

### PR DESCRIPTION
**Pull request by adiSuper94**
Related issue: #14 (Not really an issue)

Adding dns-parser to `Parsers written with nom` section of readme.

https://github.com/adiSuper94/dns-rs

### CODE REVIEW

**Comment by adiSuper94** [comment]
Let me know if you need any info or changes.

**Comment by Geal** [comment]
the repository does not exist?

**Comment by adiSuper94** [comment]
It was private. Changed the visibility just now.

**Review by Geal — APPROVED** [review]
interesting, thanks

**Pull request merged**
